  CONF_TEST:
    image: >-
      VALIDATOR_IMAGE
    environment:
      LIGHTHOUSE_NEO4J_EMBEDDED: 'false'
      LIGHTHOUSE_RABBITMQ_EMBEDDED: 'false'
      LIGHTHOUSE_PAPYRUS_EMBEDDED: 'false'
      LIGHTHOUSE_VPR_EMBEDDED: 'false'
      LIGHTHOUSE_NEO4J_SERVER_URI: 'bolt://neo4j'
      LIGHTHOUSE_EVENT_NOTIFIER_RABBITMQ_HOSTNAME: 'rabbitmq'
      BACKEND_SUCCESS_RESULT: >-
        SUCCEEDING_WITH
      BACKEND_HEALTH_ENDPOINT: 'PLACE_TO_HIT'
      BACKEND_STARTUP_ARGS: >-
        STARTUP_ARGUMENTS
      CONFIG_TESTER_RESPONSE_READY: >-
        READY_RESPONSE
      UNIT: >-
        CONFIG_UNIT
    depends_on:
      - neo4j
    entrypoint: |
      sh -c '
      command -v apk > /dev/null || (command -v apt-get >/dev/null && apt-get update)
      command -v curl > /dev/null || apk add curl || apt-get install curl
      mkdir -p /app/conf/domain
      (
        cd /app/conf/domain
        curl -s http://CONFIG_SERVER/CONFIG_UNIT.tar.gz | tar zx
      )
      curl -s http://CONFIG_SERVER/run-script > /tmp/script
      chmod +x /tmp/script
      /tmp/script
      '
