services:
  neo4j:
    image: gcr.io/helical-crowbar-220917/neo4j-with-demo-data:latest
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
      - 2004:2004
    environment:
      NEO4J_AUTH: NEO4J_CREDENTIALS
      NEO4J_dbms_logs_query_enabled: 'true'
      NEO4J_metrics_prometheus_enabled: 'true'
      NEO4J_metrics_prometheus_endpoint: 0.0.0.0:2004
      NEO4J_dbms_jvm_additional: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
